### ISSUE TITLE
Debian package installs plugin into wrong path

### ISSUE THREAD

**Issue by julijane** [cg2121/obs-vintage-filter#1]
The debian package puts the plugin into /usr/lib/obs-plugins (only). This did not work on my system. I had to copy the file to /usr/lib/x86_64-linux-gnu/obs-plugins to make it working.

I noticed that another plugin (websocket) installs into both locations, so I guess you should do the same.

**Comment by cg2121** [comment]
Fixed by: https://github.com/cg2121/obs-vintage-filter/commit/5358831e3c4118e0db14f2513958cb6c0c9e5a82
